site_name: IUEditor Manual
pages:
  - ['index.md', 'Home']
  - ['Introduction/what-is-the-iueditor.md', '소개 Introduction', '아이유에디터가 뭐에요?']
  - ['Introduction/environment.md', '소개 Introduction', '구동환경은?']
  
  - ['Features/top-tool-bar.md', '기능설명 Features', '상단 툴바 Top Toolbar']
  - ['Features/middle-tool-bar.md', '기능설명 Features', '중앙 툴바 Middel Toolbar']
  - ['Features/navigation.md', '기능설명 Features', '네비게이션 Navigation']
  - ['Features/resource-panel.md', '기능설명 Features', '리소스 패널 Resource Panel']
  - ['Features/event-panel.md', '기능설명 Features', '이벤트 패널 Event Panel']
  
  - ['Steps/static-web.md', '웹사이트 만들기 Creating Website', '정적인 웹사이트 제작']

  - ['Widget/box.md', '위젯 속성 Widget Property', '박스 Box']
  - ['Widget/text.md', '위젯 속성 Widget Property', '텍스트 Text']
  - ['Widget/image.md', '위젯 속성 Widget Property', '이미지 Image']
  - ['Widget/transition.md', '위젯 속성 Widget Property', '트랜지션 Transition']
  - ['Widget/carousel.md', '위젯 속성 Widget Property', '캐러젤 Carousel']
  - ['Widget/googlemap.md', '위젯 속성 Widget Property', '구글맵 Google Map']
  - ['Widget/webmovie.md', '위젯 속성 Widget Property', '웹무비 Web Movie']
  - ['Widget/videoclip.md', '위젯 속성 Widget Property', '비디오클립 Video Clip']
  - ['Widget/import.md', '위젯 속성 Widget Property', '임포트 Import']
  - ['Widget/tweet.md', '위젯 속성 Widget Property', '트윗 공유 버튼 Tweet Share Button']
  - ['Widget/facebook.md', '위젯 속성 Widget Property', '페이스북 좋아요 버튼 Facebook Like Button']
  - ['Widget/centeredbox.md', '위젯 속성 Widget Property', '센터박스 Centered Box']
  - ['Widget/form.md', '위젯 속성 Widget Property', '폼 Form']
  - ['Widget/textfield.md', '위젯 속성 Widget Property', '텍스트필드 Input Text']
  - ['Widget/textarea.md', '위젯 속성 Widget Property', '텍스트영역 Input Paragrapth Text']
  - ['Widget/submit.md', '위젯 속성 Widget Property', '서브밋 버튼 Submit Button']
  - ['Widget/html.md', '위젯 속성 Widget Property', 'HTML']
  
  - ['Knownbug/known-bug.md', '알려진 버그 Known Bug', '알려진 버그 리스트']

  - ['Appendix/appendix-shortcut.md', '부록 Appendix', '단축키 Shortcut']  
  - ['Appendix/appendix-voca.md', '부록 Appendix', '용어 설명']
  


theme: readthedocs
site_author: "iu@jdlab.org"
repo_url: https://github.com/IUEditor-Manual/iumanual.git


include_search : true
include_nav : true
include_next_prev : true
use_directory_urls : false
