site_name: IUEditor Manual
pages:
  - ['index.md', 'Home']
  - ['Introduction/what-is-the-iueditor.md', '소개 Introduction', '아이유에디터가 뭐에요?']
  - ['Introduction/environment.md', '소개 Introduction', '구동환경은?']
  
  - ['Features/top-tool-bar.md', '기능설명 Features', '상단 툴바 Top Toolbar']
  - ['Features/middle-tool-bar.md', '기능설명 Features', '중앙 툴바 Middel Toolbar']
  - ['Features/navigation.md', '기능설명 Features', '네비게이션 Navigation']
  - ['Features/resource-panel.md', '기능설명 Features', '리소스 패널 Resource Panel']
  - ['Features/event-panel.md', '기능설명 Features', '이벤트 패널 Event Panel']
  
  - ['Steps/static-web.md', '웹사이트 만들기 Creating Website', '정적인 웹사이트 제작']

  - ['Sheet/page.md', '시트 Sheet', '페이지 Page']
  - ['Sheet/composition.md', '시트 Sheet', '컴포지션 Composition']

  - ['Widget/basic.md', '위젯 Widget', '기본 위젯 Basic Widget']
  - ['Widget/complex.md', '위젯 Widget', '복합 위젯 Complex Widget']
  - ['Widget/programming.md', '위젯 Widget', '프로그래밍 위젯 Programming Widget']
    
  - ['Knownbug/known-bug.md', '알려진 버그 Known Bug', '알려진 버그 리스트']

  - ['Appendix/appendix-shortcut.md', '부록 Appendix', '단축키 Shortcut']  
  - ['Appendix/appendix-voca.md', '부록 Appendix', '용어 설명']
  


theme: readthedocs
site_author: "iu@jdlab.org"
repo_url: https://github.com/IUEditor-Manual/iumanual.git


include_search : true
include_nav : true
include_next_prev : true
use_directory_urls : false
